language: rust
dist: trusty
cache: cargo
sudo: false
os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly-2017-06-19

matrix:
  allow_failures:
    - rust: nightly

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly-2017-06-19" ]]; then
      cargo install --force clippy;
    fi

script:
  - cargo build --verbose --all
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly-2017-06-19" &&
      -f ~/.cargo/bin/cargo-clippy ]]; then
      cargo clippy;
    fi
  - cargo test --verbose --all
