language: rust

dist: trusty

rust:
  - nightly-2017-06-19

os:
  - linux

sudo: false

cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly

# Add clippy
before_script:
  - export PATH=$PATH:~/.cargo/bin
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly-2017-06-19" && ! -f ~/.cargo/bin/cargo-clippy]]; cargo install clippy; fi

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - echo "Rust version $TRAVIS_RUST_VERSION"
  - echo "Test X$CLIPPY"
  - echo "Path $PATH"
  - test "$TRAVIS_RUST_VERSION" == "nightly-2017-06-19" \
    && test -f ~/.cargo/bin/cargo-clippy \
      && cargo clippy;
