language: rust

dist: trusty

rust:
  - stable
  - beta
  - nightly

os:
  - linux

sudo: false

cache:
  cargo: true

matrix:
  allow_failures:
    - rust: nightly

# Add clippy
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
      fi
  - export PATH=$PATH:~/.cargo/bin

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - |
      echo "X$CLIPPY" &&
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" && $CLIPPY ]]; then
        cargo clippy;
      fi
